# Generated by Django 5.2.7 on 2026-01-05 16:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project_url', models.URLField(blank=True, help_text='Link to live project or demo', max_length=500, null=True, validators=[django.core.validators.URLValidator()])),
                ('image', models.ImageField(blank=True, help_text='Project screenshot or image', null=True, upload_to='portfolio/')),
                ('technologies', models.TextField(blank=True, help_text="Comma-separated list of technologies used (e.g., 'React, Node.js, PostgreSQL')", null=True)),
                ('date_completed', models.DateField(blank=True, help_text='Project completion date', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured items are displayed prominently')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'verbose_name_plural': 'Portfolio Items',
                'db_table': 'portfolio_items',
                'ordering': ['order', '-date_completed', '-created_at'],
                'indexes': [models.Index(fields=['user', 'order'], name='portfolio_i_user_id_469f3a_idx'), models.Index(fields=['user', 'is_featured'], name='portfolio_i_user_id_de36b0_idx')],
            },
        ),
    ]
