# Generated by Django 5.2.7 on 2025-12-06 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_task_applications', models.BooleanField(default=True)),
                ('email_task_updates', models.BooleanField(default=True)),
                ('email_messages', models.BooleanField(default=True)),
                ('email_task_reminders', models.BooleanField(default=True)),
                ('email_marketing', models.BooleanField(default=False)),
                ('push_task_applications', models.BooleanField(default=True)),
                ('push_task_updates', models.BooleanField(default=True)),
                ('push_messages', models.BooleanField(default=True)),
                ('push_task_reminders', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_application', 'Task Application'), ('application_accepted', 'Application Accepted'), ('application_rejected', 'Application Rejected'), ('task_completed', 'Task Completed'), ('task_cancelled', 'Task Cancelled'), ('new_message', 'New Message'), ('task_reminder', 'Task Reminder'), ('payment_received', 'Payment Received'), ('review_received', 'Review Received'), ('task_update', 'Task Update'), ('system', 'System Notification')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('application_id', models.IntegerField(blank=True, null=True)),
                ('message_id', models.IntegerField(blank=True, null=True)),
                ('sender_id', models.IntegerField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
