# Generated by Django 5.2.7 on 2025-12-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='listing_type',
            field=models.CharField(choices=[('task_request', 'Task Request'), ('service_offer', 'Service Offer')], default='task_request', max_length=20),
        ),
    ]
