# Generated by Django 5.2.7 on 2025-12-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_listing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('DIGITAL', 'Digital'), ('BOTH', 'Both'), ('ONE_TIME', 'One Time'), ('RECURRING', 'Recurring')], default='PHYSICAL', max_length=20),
        ),
    ]
