# Generated by Django 5.2.7 on 2025-12-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_skill_userskill_skill_skills_categor_82208c_idx_and_more'),
        ('tasks', '0003_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='required_skills',
            field=models.ManyToManyField(blank=True, help_text='Structured skills required for this task', related_name='tasks_requiring', to='recommendations.skill'),
        ),
    ]
