# Generated by Django 5.2.7 on 2025-12-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_required_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final agreed amount (from accepted application)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Payment'), ('escrowed', 'Escrowed'), ('released', 'Released'), ('refunded', 'Refunded')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='requires_payment',
            field=models.BooleanField(default=True, help_text='Whether this task requires escrow payment'),
        ),
    ]
