# Generated by Django 5.2.7 on 2026-01-24 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_final_amount_task_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, help_text='Personal note about this saved task', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Task',
                'verbose_name_plural': 'Saved Tasks',
                'db_table': 'saved_tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='saved_tasks_user_id_b68e0f_idx')],
                'unique_together': {('user', 'task')},
            },
        ),
    ]
