# Generated by Django 5.2.7 on 2025-11-14 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_categories', models.TextField(blank=True, help_text='Comma-separated category IDs', null=True)),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_location', models.CharField(blank=True, max_length=200, null=True)),
                ('max_distance', models.IntegerField(blank=True, help_text='Maximum distance in km', null=True)),
                ('prefer_remote', models.BooleanField(default=False)),
                ('prefer_physical', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('TASK', 'Task Recommendation'), ('FREELANCER', 'Freelancer Recommendation')], max_length=20)),
                ('recommended_items', models.TextField(help_text='JSON array of recommended item IDs')),
                ('recommendation_scores', models.TextField(blank=True, help_text='JSON object with scores', null=True)),
                ('algorithm_used', models.CharField(default='hybrid', help_text="e.g., 'tfidf', 'semantic', 'hybrid'", max_length=50)),
                ('clicked_items', models.TextField(blank=True, help_text='JSON array of clicked item IDs', null=True)),
                ('applied_items', models.TextField(blank=True, help_text='JSON array of applied item IDs', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation Log',
                'verbose_name_plural': 'Recommendation Logs',
                'db_table': 'recommendation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='recommendat_user_id_6bf830_idx'), models.Index(fields=['recommendation_type'], name='recommendat_recomme_1fb3c6_idx')],
            },
        ),
    ]
