# Generated by Django 5.2.7 on 2025-12-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_add_onboarding_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_categories',
            field=models.TextField(blank=True, help_text='Comma-separated category IDs (legacy, use interests instead)', null=True),
        ),
    ]
