# Generated by Django 5.2.7 on 2025-12-12 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_userpreference_preferred_categories'),
        ('tasks', '0003_alter_task_task_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Skill name (e.g., 'Python Programming', 'Graphic Design')", max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('creative', 'Creative'), ('business', 'Business'), ('manual', 'Manual Labor'), ('service', 'Service'), ('education', 'Education'), ('health', 'Health & Wellness'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0, help_text='How many users have this skill (for popularity sorting)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_task_categories', models.ManyToManyField(blank=True, help_text='Task categories this skill is relevant to', related_name='related_skills', to='tasks.category')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 'skills',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('years_experience', models.IntegerField(blank=True, help_text='Years of experience with this skill', null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='recommendations.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Skill',
                'verbose_name_plural': 'User Skills',
                'db_table': 'user_skills',
                'ordering': ['-is_primary', '-proficiency', 'skill__name'],
            },
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category', '-usage_count'], name='skills_categor_82208c_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['is_active'], name='skills_is_acti_8d0eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['user', 'is_primary'], name='user_skills_user_id_b6f040_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('user', 'skill')},
        ),
    ]
